# .pre-commit-config.yaml
repos:

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.32.0
    hooks:
      - id: yapf
        additional_dependencies: ['toml']

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: ["--max-line-length=120"]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.29.1
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=10240"]  # 10MB in kilobytes (10,240 KB)
      - id: check-case-conflict

  - repo: local
    hooks:
      - id: sphinx-docs
        name: Generate Sphinx Documentation
        entry: bash -c 'cd docs && poetry run sphinx-apidoc -o source ../ && make html'
        language: system
        files: '^(python_lib_examples|pytorch_tutorials|leetcode|jz_python_chest)/'
      - id: update-requirements
        name: Update requirements.txt from pyproject.toml
        entry: bash -c 'poetry export --without-hashes -f requirements.txt -o requirements.txt'
        language: system
        pass_filenames: false
