name: pre-commit

on:
  pull_request:
    branches:
      - master

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Run pre-commit
        run: |
          pip install poetry
          pip install pre-commit
          poetry install
          export PATH=$(poetry env info --path)/bin:$PATH
          pre-commit install
          pre-commit run --all-files
